title: Sanjeet Jagdale
#logo: /assets/img/headshot_circle.png
description: Data nerd . Creativity . Learning 
+91 9370132627 | sanjeetjagdale7@gmail.com 
link: https://www.linkedin.com/in/sanjeet-jagdale/
Pune, Maharashtra

#show_downloads: true
theme: jekyll-theme-minimal
