title: Sanjeet Jagdale
#logo: /assets/img/headshot_circle.png
description: Data nerd . Creativity . Learning
- +91 9370132627 | sanjeetjagdale7@gmail.com 
- Pune, Maharashtra
- ![Linkdin] (https://www.linkedin.com/in/sanjeet-jagdale/)
#show_downloads: true
theme: jekyll-theme-minimal
